"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
exports.__esModule = true;
exports.ProductInfo = exports.ProductImage = exports.ProductItemWrapper = exports.StatusItem = exports.OrderSummaryContainer = exports.SectionContent = exports.SectionHeader = exports.SectionWrapper = exports.MenuItem = exports.MyMenu = exports.Button = exports.AccountInfoBox = exports.ContentContainer = exports.SidebarContainer = exports.LayoutContainer = void 0;
// src/components/MyPage/MyPageStyles.ts
var styled_components_1 = __importDefault(require("styled-components"));
// --- 기본 레이아웃 ---
exports.LayoutContainer = styled_components_1["default"].div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  max-width: 1200px;\n  margin: 50px auto;\n  padding: 0 20px;\n  display: flex;\n  gap: 30px;\n  font-family: Arial, sans-serif;\n"], ["\n  max-width: 1200px;\n  margin: 50px auto;\n  padding: 0 20px;\n  display: flex;\n  gap: 30px;\n  font-family: Arial, sans-serif;\n"])));
exports.SidebarContainer = styled_components_1["default"].div(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  width: 200px;\n  flex-shrink: 0;\n"], ["\n  width: 200px;\n  flex-shrink: 0;\n"])));
exports.ContentContainer = styled_components_1["default"].div(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  flex-grow: 1;\n"], ["\n  flex-grow: 1;\n"])));
// --- 사이드바 요소 ---
exports.AccountInfoBox = styled_components_1["default"].div(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  background: #000;\n  color: #fff;\n  padding: 20px;\n  margin-bottom: 20px;\n  height: 300px;\n\n  h3 {\n    font-size: 16px;\n    margin-bottom: 10px;\n  }\n  p {\n    font-size: 14px;\n    margin-bottom: 5px;\n  }\n"], ["\n  background: #000;\n  color: #fff;\n  padding: 20px;\n  margin-bottom: 20px;\n  height: 300px;\n\n  h3 {\n    font-size: 16px;\n    margin-bottom: 10px;\n  }\n  p {\n    font-size: 14px;\n    margin-bottom: 5px;\n  }\n"])));
exports.Button = styled_components_1["default"].button(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n  width: 100%;\n  padding: 10px;\n  margin-top: 10px;\n  background: none;\n  border: 1px solid #fff;\n  color: #fff;\n  cursor: pointer;\n  transition: background-color 0.2s;\n\n  &:hover {\n    background: #333;\n  }\n"], ["\n  width: 100%;\n  padding: 10px;\n  margin-top: 10px;\n  background: none;\n  border: 1px solid #fff;\n  color: #fff;\n  cursor: pointer;\n  transition: background-color 0.2s;\n\n  &:hover {\n    background: #333;\n  }\n"])));
exports.MyMenu = styled_components_1["default"].div(templateObject_6 || (templateObject_6 = __makeTemplateObject(["\n  border: 1px solid #eee;\n"], ["\n  border: 1px solid #eee;\n"])));
exports.MenuItem = styled_components_1["default"].div(templateObject_7 || (templateObject_7 = __makeTemplateObject(["\n  display: flex;\n  justify-content: space-between;\n  padding: 12px 15px;\n  font-size: 14px;\n  cursor: pointer;\n  border-bottom: 1px solid #eee;\n  font-weight: ", ";\n  background-color: ", ";\n\n  &:hover {\n    background-color: #f9f9f9;\n  }\n"], ["\n  display: flex;\n  justify-content: space-between;\n  padding: 12px 15px;\n  font-size: 14px;\n  cursor: pointer;\n  border-bottom: 1px solid #eee;\n  font-weight: ", ";\n  background-color: ", ";\n\n  &:hover {\n    background-color: #f9f9f9;\n  }\n"])), function (props) { return (props.$active ? "bold" : "normal"); }, function (props) { return (props.$active ? "#f5f5f5" : "#fff"); });
// --- 콘텐츠 요소 ---
exports.SectionWrapper = styled_components_1["default"].div(templateObject_8 || (templateObject_8 = __makeTemplateObject(["\n  margin-bottom: 40px;\n  border: 1px solid #eee;\n"], ["\n  margin-bottom: 40px;\n  border: 1px solid #eee;\n"])));
exports.SectionHeader = styled_components_1["default"].div(templateObject_9 || (templateObject_9 = __makeTemplateObject(["\n  display: flex;\n  justify-content: space-between;\n  padding: 15px 20px;\n  background: #f9f9f9;\n  font-weight: bold;\n  border-bottom: 1px solid #eee;\n  cursor: pointer;\n"], ["\n  display: flex;\n  justify-content: space-between;\n  padding: 15px 20px;\n  background: #f9f9f9;\n  font-weight: bold;\n  border-bottom: 1px solid #eee;\n  cursor: pointer;\n"])));
exports.SectionContent = styled_components_1["default"].div(templateObject_10 || (templateObject_10 = __makeTemplateObject(["\n  padding: 20px;\n"], ["\n  padding: 20px;\n"])));
// --- 주문 상태 요약 ---
exports.OrderSummaryContainer = (0, styled_components_1["default"])(exports.SectionWrapper)(templateObject_11 || (templateObject_11 = __makeTemplateObject(["\n  display: flex;\n  border: none;\n  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.05);\n  background: #f9f9f9;\n  margin-bottom: 30px;\n"], ["\n  display: flex;\n  border: none;\n  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.05);\n  background: #f9f9f9;\n  margin-bottom: 30px;\n"])));
exports.StatusItem = styled_components_1["default"].div(templateObject_12 || (templateObject_12 = __makeTemplateObject(["\n  flex: 1;\n  text-align: center;\n  padding: 20px 0;\n  border-right: 1px solid #ddd;\n\n  &:last-child {\n    border-right: none;\n  }\n\n  p:first-child {\n    font-size: 14px;\n    color: #666;\n    margin-bottom: 10px;\n  }\n\n  span {\n    display: block;\n    font-size: 24px;\n    font-weight: bold;\n    color: #333;\n  }\n"], ["\n  flex: 1;\n  text-align: center;\n  padding: 20px 0;\n  border-right: 1px solid #ddd;\n\n  &:last-child {\n    border-right: none;\n  }\n\n  p:first-child {\n    font-size: 14px;\n    color: #666;\n    margin-bottom: 10px;\n  }\n\n  span {\n    display: block;\n    font-size: 24px;\n    font-weight: bold;\n    color: #333;\n  }\n"])));
// --- 상품 목록 요소 ---
exports.ProductItemWrapper = styled_components_1["default"].div(templateObject_13 || (templateObject_13 = __makeTemplateObject(["\n  display: flex;\n  padding: 15px 0;\n  border-bottom: 1px solid #eee;\n"], ["\n  display: flex;\n  padding: 15px 0;\n  border-bottom: 1px solid #eee;\n"])));
exports.ProductImage = styled_components_1["default"].div(templateObject_14 || (templateObject_14 = __makeTemplateObject(["\n  width: 80px;\n  height: 80px;\n  background: #eee;\n  margin-right: 15px;\n"], ["\n  width: 80px;\n  height: 80px;\n  background: #eee;\n  margin-right: 15px;\n"])));
exports.ProductInfo = styled_components_1["default"].div(templateObject_15 || (templateObject_15 = __makeTemplateObject(["\n  flex-grow: 1;\n\n  p {\n    font-size: 13px;\n    color: #666;\n    margin-bottom: 4px;\n  }\n  span {\n    font-size: 14px;\n    font-weight: bold;\n  }\n"], ["\n  flex-grow: 1;\n\n  p {\n    font-size: 13px;\n    color: #666;\n    margin-bottom: 4px;\n  }\n  span {\n    font-size: 14px;\n    font-weight: bold;\n  }\n"])));
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6, templateObject_7, templateObject_8, templateObject_9, templateObject_10, templateObject_11, templateObject_12, templateObject_13, templateObject_14, templateObject_15;
