"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
exports.__esModule = true;
exports.ActionButton = exports.BuyButton = exports.ButtonGroup = exports.PriceText = exports.InfoRow = exports.InfoTable = exports.ArtistName = exports.Title = exports.InfoArea = exports.ImageArea = exports.MainContent = exports.HamburgerMenu = exports.SidebarIcon = exports.LeftSidebar = exports.PageLayout = void 0;
// src/components/ProductDetail/ProductDetailStyles.ts
var styled_components_1 = __importDefault(require("styled-components"));
exports.PageLayout = styled_components_1["default"].div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  display: flex;\n  min-height: 100vh;\n  background-color: #fff;\n  font-family: Arial, sans-serif;\n"], ["\n  display: flex;\n  min-height: 100vh;\n  background-color: #fff;\n  font-family: Arial, sans-serif;\n"])));
// --- 사이드바 영역 ---
exports.LeftSidebar = styled_components_1["default"].div(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  width: 50px; /* \uACE0\uC815\uB41C \uC881\uC740 \uB108\uBE44 */\n  background-color: #000;\n  color: #fff;\n  display: flex;\n  flex-direction: column;\n  align-items: center;\n  padding-top: 20px;\n"], ["\n  width: 50px; /* \uACE0\uC815\uB41C \uC881\uC740 \uB108\uBE44 */\n  background-color: #000;\n  color: #fff;\n  display: flex;\n  flex-direction: column;\n  align-items: center;\n  padding-top: 20px;\n"])));
exports.SidebarIcon = styled_components_1["default"].div(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  padding: 15px 0;\n  cursor: pointer;\n  font-size: 20px;\n  opacity: 0.7;\n  transition: opacity 0.2s;\n\n  &:hover {\n    opacity: 1;\n  }\n"], ["\n  padding: 15px 0;\n  cursor: pointer;\n  font-size: 20px;\n  opacity: 0.7;\n  transition: opacity 0.2s;\n\n  &:hover {\n    opacity: 1;\n  }\n"])));
exports.HamburgerMenu = (0, styled_components_1["default"])(exports.SidebarIcon)(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  margin-bottom: 20px;\n  font-size: 24px;\n"], ["\n  margin-bottom: 20px;\n  font-size: 24px;\n"])));
// --- 메인 콘텐츠 영역 ---
exports.MainContent = styled_components_1["default"].div(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n  flex-grow: 1;\n  display: flex;\n  padding: 40px;\n"], ["\n  flex-grow: 1;\n  display: flex;\n  padding: 40px;\n"])));
exports.ImageArea = styled_components_1["default"].div(templateObject_6 || (templateObject_6 = __makeTemplateObject(["\n  flex: 1;\n  padding-right: 40px;\n\n  img {\n    width: 100%;\n    min-width: 500px;\n    max-width: 600px;\n    height: auto;\n    background-color: #f0f0f0; /* \uD50C\uB808\uC774\uC2A4\uD640\uB354 \uBC30\uACBD */\n    border: 1px solid #eee;\n  }\n"], ["\n  flex: 1;\n  padding-right: 40px;\n\n  img {\n    width: 100%;\n    min-width: 500px;\n    max-width: 600px;\n    height: auto;\n    background-color: #f0f0f0; /* \uD50C\uB808\uC774\uC2A4\uD640\uB354 \uBC30\uACBD */\n    border: 1px solid #eee;\n  }\n"])));
exports.InfoArea = styled_components_1["default"].div(templateObject_7 || (templateObject_7 = __makeTemplateObject(["\n  width: 350px; /* \uC815\uBCF4 \uC601\uC5ED \uACE0\uC815 \uB108\uBE44 */\n  padding-left: 20px;\n"], ["\n  width: 350px; /* \uC815\uBCF4 \uC601\uC5ED \uACE0\uC815 \uB108\uBE44 */\n  padding-left: 20px;\n"])));
// --- 정보 테이블 ---
exports.Title = styled_components_1["default"].h1(templateObject_8 || (templateObject_8 = __makeTemplateObject(["\n  font-size: 26px;\n  font-weight: normal;\n  margin-bottom: 5px;\n  color: #333;\n"], ["\n  font-size: 26px;\n  font-weight: normal;\n  margin-bottom: 5px;\n  color: #333;\n"])));
exports.ArtistName = styled_components_1["default"].h2(templateObject_9 || (templateObject_9 = __makeTemplateObject(["\n  font-size: 18px;\n  font-weight: 500;\n  margin-bottom: 30px;\n  color: #666;\n"], ["\n  font-size: 18px;\n  font-weight: 500;\n  margin-bottom: 30px;\n  color: #666;\n"])));
exports.InfoTable = styled_components_1["default"].div(templateObject_10 || (templateObject_10 = __makeTemplateObject(["\n  margin-bottom: 30px;\n  border-bottom: 1px solid #ddd;\n  padding-bottom: 10px;\n"], ["\n  margin-bottom: 30px;\n  border-bottom: 1px solid #ddd;\n  padding-bottom: 10px;\n"])));
exports.InfoRow = styled_components_1["default"].div(templateObject_11 || (templateObject_11 = __makeTemplateObject(["\n  display: flex;\n  padding: 8px 0;\n  border-top: 1px solid #eee;\n\n  span:first-child {\n    flex-basis: 100px;\n    font-weight: normal;\n    color: #666;\n    font-size: 14px;\n  }\n\n  span:last-child {\n    flex-grow: 1;\n    font-weight: 500;\n    color: #333;\n    font-size: 14px;\n  }\n"], ["\n  display: flex;\n  padding: 8px 0;\n  border-top: 1px solid #eee;\n\n  span:first-child {\n    flex-basis: 100px;\n    font-weight: normal;\n    color: #666;\n    font-size: 14px;\n  }\n\n  span:last-child {\n    flex-grow: 1;\n    font-weight: 500;\n    color: #333;\n    font-size: 14px;\n  }\n"])));
// --- 가격 및 버튼 ---
exports.PriceText = styled_components_1["default"].div(templateObject_12 || (templateObject_12 = __makeTemplateObject(["\n  font-size: 22px;\n  font-weight: bold;\n  margin-bottom: 25px;\n  color: #a00;\n"], ["\n  font-size: 22px;\n  font-weight: bold;\n  margin-bottom: 25px;\n  color: #a00;\n"])));
exports.ButtonGroup = styled_components_1["default"].div(templateObject_13 || (templateObject_13 = __makeTemplateObject(["\n  display: flex;\n  gap: 10px;\n"], ["\n  display: flex;\n  gap: 10px;\n"])));
exports.BuyButton = styled_components_1["default"].button(templateObject_14 || (templateObject_14 = __makeTemplateObject(["\n  flex-grow: 1;\n  padding: 12px 20px;\n  background-color: #ccc; /* \uC774\uBBF8\uC9C0\uC640 \uC720\uC0AC\uD55C \uD68C\uC0C9 */\n  border: none;\n  color: #fff;\n  font-size: 16px;\n  cursor: pointer;\n  transition: background-color 0.2s;\n\n  &:hover {\n    background-color: #a0a0a0;\n  }\n"], ["\n  flex-grow: 1;\n  padding: 12px 20px;\n  background-color: #ccc; /* \uC774\uBBF8\uC9C0\uC640 \uC720\uC0AC\uD55C \uD68C\uC0C9 */\n  border: none;\n  color: #fff;\n  font-size: 16px;\n  cursor: pointer;\n  transition: background-color 0.2s;\n\n  &:hover {\n    background-color: #a0a0a0;\n  }\n"])));
exports.ActionButton = (0, styled_components_1["default"])(exports.BuyButton)(templateObject_15 || (templateObject_15 = __makeTemplateObject(["\n  flex-grow: 0;\n  width: 120px;\n  background-color: #fff;\n  border: 1px solid #ccc;\n  color: #333;\n\n  &:hover {\n    background-color: #f5f5f5;\n  }\n"], ["\n  flex-grow: 0;\n  width: 120px;\n  background-color: #fff;\n  border: 1px solid #ccc;\n  color: #333;\n\n  &:hover {\n    background-color: #f5f5f5;\n  }\n"])));
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6, templateObject_7, templateObject_8, templateObject_9, templateObject_10, templateObject_11, templateObject_12, templateObject_13, templateObject_14, templateObject_15;
