"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
exports.__esModule = true;
exports.ProductInfo = exports.ProductSummaryBlock = exports.FinalButton = exports.FinalPrice = exports.SummaryRow = exports.SummaryColumn = exports.RadioLabel = exports.PaymentMethod = exports.SelectBox = exports.InputField = exports.FormRow = exports.InfoBlock = exports.InputColumn = exports.SectionTitle = exports.SectionWrapper = exports.MainGrid = exports.LayoutContainer = void 0;
// src/components/Checkout/CheckoutStyles.ts
var styled_components_1 = __importDefault(require("styled-components"));
// --- 기본 레이아웃 ---
exports.LayoutContainer = styled_components_1["default"].div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  max-width: 1200px;\n  margin: 50px auto;\n  padding: 0 20px;\n  font-family: Arial, sans-serif;\n"], ["\n  max-width: 1200px;\n  margin: 50px auto;\n  padding: 0 20px;\n  font-family: Arial, sans-serif;\n"])));
exports.MainGrid = styled_components_1["default"].div(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  display: grid;\n  grid-template-columns: 2fr 1fr; /* \uC88C\uCE21 \uC785\uB825\uD3FC 2, \uC6B0\uCE21 \uACB0\uC81C\uC694\uC57D 1 */\n  gap: 30px;\n"], ["\n  display: grid;\n  grid-template-columns: 2fr 1fr; /* \uC88C\uCE21 \uC785\uB825\uD3FC 2, \uC6B0\uCE21 \uACB0\uC81C\uC694\uC57D 1 */\n  gap: 30px;\n"])));
// --- 공통 섹션 스타일 ---
exports.SectionWrapper = styled_components_1["default"].div(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  margin-bottom: 30px;\n  padding: 20px;\n  border: 1px solid #ddd;\n  background-color: #fff;\n"], ["\n  margin-bottom: 30px;\n  padding: 20px;\n  border: 1px solid #ddd;\n  background-color: #fff;\n"])));
exports.SectionTitle = styled_components_1["default"].h2(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  font-size: 18px;\n  font-weight: bold;\n  margin-bottom: 20px;\n  padding-bottom: 10px;\n  border-bottom: 1px solid #eee;\n"], ["\n  font-size: 18px;\n  font-weight: bold;\n  margin-bottom: 20px;\n  padding-bottom: 10px;\n  border-bottom: 1px solid #eee;\n"])));
// --- 좌측 (입력 및 선택) 영역 ---
exports.InputColumn = styled_components_1["default"].div(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n  /* Left Column Container */\n"], ["\n  /* Left Column Container */\n"])));
exports.InfoBlock = styled_components_1["default"].div(templateObject_6 || (templateObject_6 = __makeTemplateObject(["\n  /* \uC8FC\uBB38\uC790 \uC815\uBCF4, \uBC30\uC1A1\uC9C0 \uC815\uBCF4 \uB4F1 */\n  margin-bottom: 20px;\n"], ["\n  /* \uC8FC\uBB38\uC790 \uC815\uBCF4, \uBC30\uC1A1\uC9C0 \uC815\uBCF4 \uB4F1 */\n  margin-bottom: 20px;\n"])));
exports.FormRow = styled_components_1["default"].div(templateObject_7 || (templateObject_7 = __makeTemplateObject(["\n  display: flex;\n  gap: 15px;\n  margin-bottom: 10px;\n  align-items: center;\n\n  > label {\n    flex-basis: 80px;\n    font-size: 14px;\n    color: #333;\n    flex-shrink: 0;\n  }\n\n  > div {\n    flex-grow: 1;\n    display: flex;\n    gap: 5px;\n    align-items: center;\n  }\n"], ["\n  display: flex;\n  gap: 15px;\n  margin-bottom: 10px;\n  align-items: center;\n\n  > label {\n    flex-basis: 80px;\n    font-size: 14px;\n    color: #333;\n    flex-shrink: 0;\n  }\n\n  > div {\n    flex-grow: 1;\n    display: flex;\n    gap: 5px;\n    align-items: center;\n  }\n"])));
exports.InputField = styled_components_1["default"].input(templateObject_8 || (templateObject_8 = __makeTemplateObject(["\n  padding: 10px;\n  border: 1px solid #ccc;\n  font-size: 14px;\n  width: 100%;\n"], ["\n  padding: 10px;\n  border: 1px solid #ccc;\n  font-size: 14px;\n  width: 100%;\n"])));
exports.SelectBox = styled_components_1["default"].select(templateObject_9 || (templateObject_9 = __makeTemplateObject(["\n  padding: 10px;\n  border: 1px solid #ccc;\n  font-size: 14px;\n  width: 100%;\n"], ["\n  padding: 10px;\n  border: 1px solid #ccc;\n  font-size: 14px;\n  width: 100%;\n"])));
// --- 결제 방식 ---
exports.PaymentMethod = styled_components_1["default"].div(templateObject_10 || (templateObject_10 = __makeTemplateObject(["\n  display: flex;\n  flex-direction: column;\n  gap: 10px;\n  margin-top: 15px;\n"], ["\n  display: flex;\n  flex-direction: column;\n  gap: 10px;\n  margin-top: 15px;\n"])));
exports.RadioLabel = styled_components_1["default"].label(templateObject_11 || (templateObject_11 = __makeTemplateObject(["\n  display: flex;\n  align-items: center;\n  font-size: 14px;\n  gap: 8px;\n  cursor: pointer;\n"], ["\n  display: flex;\n  align-items: center;\n  font-size: 14px;\n  gap: 8px;\n  cursor: pointer;\n"])));
// --- 우측 (결제 요약) 영역 ---
exports.SummaryColumn = styled_components_1["default"].div(templateObject_12 || (templateObject_12 = __makeTemplateObject(["\n  background-color: #f9f9f9;\n  padding: 20px;\n  border: 1px solid #eee;\n  height: fit-content;\n"], ["\n  background-color: #f9f9f9;\n  padding: 20px;\n  border: 1px solid #eee;\n  height: fit-content;\n"])));
exports.SummaryRow = styled_components_1["default"].div(templateObject_13 || (templateObject_13 = __makeTemplateObject(["\n  display: flex;\n  justify-content: space-between;\n  padding: 8px 0;\n  font-size: 14px;\n  border-bottom: 1px dashed #ddd;\n\n  &:last-of-type {\n    border-bottom: none;\n    font-weight: bold;\n    font-size: 16px;\n    margin-top: 10px;\n    padding-top: 10px;\n    border-top: 2px solid #333;\n  }\n"], ["\n  display: flex;\n  justify-content: space-between;\n  padding: 8px 0;\n  font-size: 14px;\n  border-bottom: 1px dashed #ddd;\n\n  &:last-of-type {\n    border-bottom: none;\n    font-weight: bold;\n    font-size: 16px;\n    margin-top: 10px;\n    padding-top: 10px;\n    border-top: 2px solid #333;\n  }\n"])));
exports.FinalPrice = styled_components_1["default"].div(templateObject_14 || (templateObject_14 = __makeTemplateObject(["\n  font-size: 26px;\n  font-weight: bold;\n  color: #333;\n  text-align: right;\n  margin-top: 20px;\n"], ["\n  font-size: 26px;\n  font-weight: bold;\n  color: #333;\n  text-align: right;\n  margin-top: 20px;\n"])));
exports.FinalButton = styled_components_1["default"].button(templateObject_15 || (templateObject_15 = __makeTemplateObject(["\n  width: 100%;\n  padding: 15px;\n  background-color: #333;\n  color: #fff;\n  border: none;\n  font-size: 16px;\n  font-weight: bold;\n  margin-top: 20px;\n  cursor: pointer;\n\n  &:hover {\n    background-color: #555;\n  }\n"], ["\n  width: 100%;\n  padding: 15px;\n  background-color: #333;\n  color: #fff;\n  border: none;\n  font-size: 16px;\n  font-weight: bold;\n  margin-top: 20px;\n  cursor: pointer;\n\n  &:hover {\n    background-color: #555;\n  }\n"])));
// --- 상품 요약 ---
exports.ProductSummaryBlock = styled_components_1["default"].div(templateObject_16 || (templateObject_16 = __makeTemplateObject(["\n  padding: 15px 0;\n  margin-bottom: 20px;\n  border-bottom: 1px solid #ddd;\n"], ["\n  padding: 15px 0;\n  margin-bottom: 20px;\n  border-bottom: 1px solid #ddd;\n"])));
exports.ProductInfo = styled_components_1["default"].div(templateObject_17 || (templateObject_17 = __makeTemplateObject(["\n  display: flex;\n  gap: 10px;\n\n  div:first-child {\n    width: 80px;\n    height: 80px;\n    background: #ccc;\n    flex-shrink: 0;\n  }\n\n  p {\n    font-size: 13px;\n    color: #666;\n  }\n  span {\n    display: block;\n    font-weight: bold;\n    color: #333;\n  }\n"], ["\n  display: flex;\n  gap: 10px;\n\n  div:first-child {\n    width: 80px;\n    height: 80px;\n    background: #ccc;\n    flex-shrink: 0;\n  }\n\n  p {\n    font-size: 13px;\n    color: #666;\n  }\n  span {\n    display: block;\n    font-weight: bold;\n    color: #333;\n  }\n"])));
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6, templateObject_7, templateObject_8, templateObject_9, templateObject_10, templateObject_11, templateObject_12, templateObject_13, templateObject_14, templateObject_15, templateObject_16, templateObject_17;
