"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
exports.__esModule = true;
exports.Separator = exports.UtilitySection = exports.NavLink = exports.NavSection = exports.LogoText = exports.LogoSection = exports.HeaderContainer = void 0;
var styled_components_1 = __importDefault(require("styled-components"));
// 폰트와 색상은 이미지에서 유추하여 임의로 지정합니다.
exports.HeaderContainer = styled_components_1["default"].header(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  position: fixed;\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n  padding: 10px 40px;\n  background: linear-gradient(to right, #ffffff, #f7f0f0);\n  border-bottom: 1px solid rgba(0, 0, 0, 0.05);\n  height: 80px;\n  top: 0px;\n  left: 0px;\n  width: 100%;\n  box-shadow: 0 3px 5px rgba(0, 0, 0, 0.05);\n  z-index: 1000;\n  margin-bottom: 100px;\n  // background: #c99c5f;\n"], ["\n  position: fixed;\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n  padding: 10px 40px;\n  background: linear-gradient(to right, #ffffff, #f7f0f0);\n  border-bottom: 1px solid rgba(0, 0, 0, 0.05);\n  height: 80px;\n  top: 0px;\n  left: 0px;\n  width: 100%;\n  box-shadow: 0 3px 5px rgba(0, 0, 0, 0.05);\n  z-index: 1000;\n  margin-bottom: 100px;\n  // background: #c99c5f;\n"])));
exports.LogoSection = styled_components_1["default"].div(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  display: flex;\n  align-items: center;\n"], ["\n  display: flex;\n  align-items: center;\n"])));
exports.LogoText = styled_components_1["default"].div(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  font-family: \"Georgia\", serif;\n  font-size: 30px;\n  font-weight: bold;\n  color: #c99c5f;\n  line-height: 1;\n\n  span {\n    display: block;\n    font-size: 12px;\n    font-weight: normal;\n    letter-spacing: 2px;\n    color: #333;\n    margin-top: 2px;\n  }\n\n  &::before {\n    content: \"A\";\n    font-size: 40px;\n    color: #c99c5f;\n    margin-right: 5px;\n  }\n"], ["\n  font-family: \"Georgia\", serif;\n  font-size: 30px;\n  font-weight: bold;\n  color: #c99c5f;\n  line-height: 1;\n\n  span {\n    display: block;\n    font-size: 12px;\n    font-weight: normal;\n    letter-spacing: 2px;\n    color: #333;\n    margin-top: 2px;\n  }\n\n  &::before {\n    content: \"A\";\n    font-size: 40px;\n    color: #c99c5f;\n    margin-right: 5px;\n  }\n"])));
exports.NavSection = styled_components_1["default"].nav(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  display: flex;\n  align-items: center;\n  flex-shrink: 0;\n  margin-right: 50px;\n"], ["\n  display: flex;\n  align-items: center;\n  flex-shrink: 0;\n  margin-right: 50px;\n"])));
exports.NavLink = styled_components_1["default"].a(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n  text-decoration: none;\n  color: #333;\n  font-size: 14px;\n  font-weight: 500;\n  margin-left: 30px;\n  padding: 5px 0;\n  cursor: pointer;\n  transition: color 0.2s;\n  &:hover {\n    color: #c99c5f;\n  }\n"], ["\n  text-decoration: none;\n  color: #333;\n  font-size: 14px;\n  font-weight: 500;\n  margin-left: 30px;\n  padding: 5px 0;\n  cursor: pointer;\n  transition: color 0.2s;\n  &:hover {\n    color: #c99c5f;\n  }\n"])));
exports.UtilitySection = styled_components_1["default"].div(templateObject_6 || (templateObject_6 = __makeTemplateObject(["\n  display: flex;\n  align-items: center;\n  margin-left: 30px;\n  gap: 10px;\n"], ["\n  display: flex;\n  align-items: center;\n  margin-left: 30px;\n  gap: 10px;\n"])));
exports.Separator = styled_components_1["default"].span(templateObject_7 || (templateObject_7 = __makeTemplateObject(["\n  color: #ccc;\n  font-size: 14px;\n  margin: 0 5px;\n"], ["\n  color: #ccc;\n  font-size: 14px;\n  margin: 0 5px;\n"])));
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6, templateObject_7;
