"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
exports.__esModule = true;
exports.ForgotPasswordLink = exports.RegisterButton = exports.LoginButton = exports.CheckboxGroup = exports.InputField = exports.Form = exports.Title = exports.FormContainer = exports.PageWrapper = void 0;
// src/components/Login/LoginStyles.ts
var styled_components_1 = __importDefault(require("styled-components"));
// --- 기본 레이아웃 ---
exports.PageWrapper = styled_components_1["default"].div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  margin-top: 30px;\n  min-height: calc(100vh - 100px); /* \uD5E4\uB354/\uD478\uD130\uB97C \uC81C\uC678\uD55C \uCD5C\uC18C \uB192\uC774 */\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  padding: 50px 20px;\n  background-color: #fff;\n  font-family: Arial, sans-serif;\n"], ["\n  margin-top: 30px;\n  min-height: calc(100vh - 100px); /* \uD5E4\uB354/\uD478\uD130\uB97C \uC81C\uC678\uD55C \uCD5C\uC18C \uB192\uC774 */\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  padding: 50px 20px;\n  background-color: #fff;\n  font-family: Arial, sans-serif;\n"])));
exports.FormContainer = styled_components_1["default"].div(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  width: 100%;\n  max-width: 400px; /* \uB85C\uADF8\uC778 \uD3FC\uC758 \uCD5C\uB300 \uB108\uBE44 */\n  text-align: center;\n"], ["\n  width: 100%;\n  max-width: 400px; /* \uB85C\uADF8\uC778 \uD3FC\uC758 \uCD5C\uB300 \uB108\uBE44 */\n  text-align: center;\n"])));
exports.Title = styled_components_1["default"].h1(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  font-size: 24px;\n  font-weight: normal;\n  margin-bottom: 40px;\n"], ["\n  font-size: 24px;\n  font-weight: normal;\n  margin-bottom: 40px;\n"])));
// --- 폼 요소 ---
exports.Form = styled_components_1["default"].form(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  display: flex;\n  flex-direction: column;\n  gap: 15px;\n"], ["\n  display: flex;\n  flex-direction: column;\n  gap: 15px;\n"])));
exports.InputField = styled_components_1["default"].input(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n  width: 100%;\n  padding: 12px 15px;\n  border: 1px solid #ccc;\n  font-size: 16px;\n  box-sizing: border-box;\n"], ["\n  width: 100%;\n  padding: 12px 15px;\n  border: 1px solid #ccc;\n  font-size: 16px;\n  box-sizing: border-box;\n"])));
exports.CheckboxGroup = styled_components_1["default"].div(templateObject_6 || (templateObject_6 = __makeTemplateObject(["\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n  font-size: 14px;\n  margin-bottom: 10px;\n\n  label {\n    display: flex;\n    align-items: center;\n    gap: 5px;\n    cursor: pointer;\n  }\n"], ["\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n  font-size: 14px;\n  margin-bottom: 10px;\n\n  label {\n    display: flex;\n    align-items: center;\n    gap: 5px;\n    cursor: pointer;\n  }\n"])));
// --- 버튼 요소 ---
exports.LoginButton = styled_components_1["default"].button(templateObject_7 || (templateObject_7 = __makeTemplateObject(["\n  width: 100%;\n  padding: 15px;\n  background-color: #333; /* \uC774\uBBF8\uC9C0 \uC18D \uC9C4\uD55C \uD68C\uC0C9 */\n  color: #fff;\n  border: none;\n  font-size: 16px;\n  font-weight: bold;\n  cursor: pointer;\n  transition: background-color 0.2s;\n\n  &:hover {\n    background-color: #555;\n  }\n"], ["\n  width: 100%;\n  padding: 15px;\n  background-color: #333; /* \uC774\uBBF8\uC9C0 \uC18D \uC9C4\uD55C \uD68C\uC0C9 */\n  color: #fff;\n  border: none;\n  font-size: 16px;\n  font-weight: bold;\n  cursor: pointer;\n  transition: background-color 0.2s;\n\n  &:hover {\n    background-color: #555;\n  }\n"])));
exports.RegisterButton = (0, styled_components_1["default"])(exports.LoginButton)(templateObject_8 || (templateObject_8 = __makeTemplateObject(["\n  background-color: #fff;\n  color: #333;\n  border: 1px solid #333;\n  margin-top: 5px;\n\n  &:hover {\n    background-color: #f0f0f0;\n  }\n"], ["\n  background-color: #fff;\n  color: #333;\n  border: 1px solid #333;\n  margin-top: 5px;\n\n  &:hover {\n    background-color: #f0f0f0;\n  }\n"])));
exports.ForgotPasswordLink = styled_components_1["default"].a(templateObject_9 || (templateObject_9 = __makeTemplateObject(["\n  display: block;\n  font-size: 12px;\n  color: #666;\n  text-decoration: none;\n  margin-top: 20px;\n\n  &:hover {\n    text-decoration: underline;\n  }\n"], ["\n  display: block;\n  font-size: 12px;\n  color: #666;\n  text-decoration: none;\n  margin-top: 20px;\n\n  &:hover {\n    text-decoration: underline;\n  }\n"])));
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6, templateObject_7, templateObject_8, templateObject_9;
